# Notification Options
notifications:
  email: false

# Regent supports Node.js v8
language: node_js
node_js:
  - '8' # LTS as of 2017-12-31

# Operating Systems
os:
  - linux
  - osx

services:
  - postgresql

addons:
  mariadb: '10.2' # latest stable version, as of 2017-12-31

# Branches that can trigger Travis-CI
branches:
  only:
    - master        # Master
    - /^regent-.*$/ # Issues

# declare your environment variables
env:
  # matrix variables will create a new build for each specified variable
  matrix:
    - NODE_ENV=development

before_script:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi
  - psql -c "CREATE DATABASE regent_test;" -U postgres
  - psql -c "CREATE USER regent WITH PASSWORD 'password123';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE regent_test TO regent;" -U postgres
  - mysql -e "CREATE DATABASE regent_test;"
  - mysql -e "GRANT ALL PRIVILEGES ON regent_test.* TO 'regent'@'localhost' IDENTIFIED BY 'password123';"

script:
  - npm run gen:coverage

after_success:
  - npm run pub:coverage
