# Notification Options
notifications:
  email: false

# Regent supports Node.js v8
language: node_js
node_js:
  - '8'

# Operating Systems
os:
  - linux

services:
  - postgresql

# Branches that can trigger Travis-CI
branches:
  only:
    - master        # Master
    - /^regent-.*$/ # Issues

# declare your environment variables
env:
  # global will stay the same across all matrix possibilities
  global:
    # - SECRET_TOKEN=k399dkkgklsk
  # matrix variables will create a new build for each specified variable
  matrix:
    # - NODE_ENV=production
    - NODE_ENV=development

# Services
services:
  # - mongodb     # will start mongodb
  # - rabbitmq # will start rabbitmq-server

## begin build steps
####################

before_install:
  - sudo apt-get -qq update

before_script:
  - npm install
  - psql -c 'CREATE DATABASE regent_test;' -U postgres
  - psql -c 'CREATE USER regent WITH PASSWORD 'password123';' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE regent_test TO regent;' -U postgres

script:
  - npm run gen:coverage

after_success:
  - npm run pub:coverage

after_faiulre:
  - echo "FAILURE"
