environment:
  nodejs_version: "8"
  matrix:
    - NODE_ENV: development
services:
  - postgresql96
  - mysql
init:
  - SET PGUSER=postgres
  - SET PGPASSWORD=postgres
  - SET PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - SET PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin\;%PATH%
  - psql --version
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build:
  - psql -c "CREATE DATABASE regent_test;" -U postgres
  - psql -c "CREATE USER regent WITH PASSWORD 'password123';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE regent_test TO regent;" -U postgres
  - mysql -e "CREATE DATABASE regent_test;" --user=root
  - mysql -e "GRANT ALL PRIVILEGES ON regent_test.* TO 'regent'@'localhost' IDENTIFIED BY 'password123';" --user=root
test_script:
  - node --version
  - npm --version
  - npm run test
