/**
 * @author Steven Jimenez <steven@stevethedev.com>
 */
'use strict';

const RegentObject = requireLib('util/regent-object');

/**
 * This class provides a standardized interface for how Regent will interact
 * with Node's standard {@link https://nodejs.org/api/http.html|HTTP Request}
 * that was generated by the {@link HttpKernel}.
 */
class Request extends RegentObject
{
    /**
     * @param {HttpKernel}           httpKernel  - The owning HTTP Kernel 
     *                                             object where this class is 
     *                                             being instantiated.
     * @param {http.IncomingMessage} httpRequest - The internal NodeJS HTTP 
     *                                             Request that this object 
     *                                             wraps.
     */
    constructor(httpKernel, httpRequest)
    {
        super(httpKernel.getRegent());

        /**
         * This is a reference to the owning HTTP kernel object which generated
         * this instance.
         * 
         * @protected
         * @type {HttpKernel}
         */
        this.__httpKernel  = httpKernel;

        /**
         * This is a reference to the internal NodeJS HTTP Request that this
         * instance wraps.
         *
         * @type {http.IncomingMessage}
         */
        this.__httpRequest = httpRequest;
    }

    /**
     * Retrieve the HTTP Method that triggered this request object.
     *
     * @return {String}
     */
    getMethod()
    {
        return this.__httpRequest.method;
    }

    /**
     * Retrieve the URI that triggered this request object, excluding the
     * scheme, host, and port.
     *
     * @return {String}
     */
    getUri()
    {
        return this.__httpRequest.url;
    }
}

module.exports = Request;
